### ISSUE TITLE
Not compatible with Brave 5.x

### ISSUE THREAD

**Issue by b-devinssuresh-cvet** [SmartThingsOSS/smartthings-brave#28]
When trying to use `smartthings-brave-sqs` in a sleuth app I ran into a compatibility issue:

```
ava.lang.NoSuchMethodError: brave.Tracer.newTrace(Lbrave/propagation/SamplingFlags;)Lbrave/Span;
	at smartthings.brave.sqs.TracingAmazonSQSClient.receiveMessage(TracingAmazonSQSClient.java:251) ~[smartthings-brave-sqs-0.5.1.jar:na]
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.receiveMessage(AmazonSQSMessagingClientWrapper.java:351) ~[amazon-sqs-java-messaging-lib-1.0.5.jar:na]
	at com.amazon.sqs.javamessaging.SQSMessageConsumerPrefetch.getMessages(SQSMessageConsumerPrefetch.java:262) ~[amazon-sqs-java-messaging-lib-1.0.5.jar:na]
	at com.amazon.sqs.javamessaging.SQSMessageConsumerPrefetch.run(SQSMessageConsumerPrefetch.java:221) ~[amazon-sqs-java-messaging-lib-1.0.5.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
```

Are there plans to update? Or are you open to updating if I file a PR?

**Comment by llinder** [comment]
There isn't any work underway to fix this yet.  I'm sure if/when we hit this it will get fixed.  In the mean time if you or anyone else has bandwidth to make a pull request it would definitely be appreciated and gladly accepted.

**Comment by llinder** [comment]
I'm also open to moving the SQS part or other parts of this library to `openzipkin-contrib` or `openzipkin/zipkin-aws`.  Not to say that should happen now but just mentioning in case it's a desirable path for anyone.

**Comment by YasinK-IW** [comment]
This would be a massive help if it worked with Brave 5.x :)

**Comment by devinsba** [comment]
I started the update: https://github.com/SmartThingsOSS/smartthings-brave/pull/29

I think the SQS/SNS pieces we should discuss on dev@zipkin.apache.org
